server:
  port: 9000
spring:
  application:    name: employee-service
  datasource:    username: root
    password: Asish@123$
    url: jdbc:mysql://localhost:3306/sys
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    hibernate:      ddl-auto: update
    show-sql: true